spring:
  application:
    name: mcc-gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  main:
    web-application-type: reactive
server:
  port: ${SERVER_PORT:8080}
microservices:
  customer-service-url: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
  account-service-url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
  credit-disbursement-service-url: ${CREDIT_DISBURSEMENT_URL:http://localhost:8082}
springdoc:
  api-docs:
    enable: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Customer Service
        url: /v3/api-docs/customers
      - name: Account service
        url: /v3/api-docs/accounts
      - name: Credit Disbursement Service
        url: /v3/api-docs/credit-disbursements
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5 # Número de llamadas que monitorea antes de cambiar de estado
        minimum-number-of-calls: 3 # Minimo de llamadas para evaluar el estado
        failure-rate-threshold: 50 # Si el 50% de las ultimas 5 llamadas fallan, el circuito de abre
        wait-duration-in-open-state: 10s # Tiempo qye espera antes de probar si el servicio volvio
        permitted-number-of-calls-in-half-open-state: 2 # Intentos en HALF-OPEN antes de cerrar

  timelimiter:
    instances:
      customerCircuitBreaker:
        timeout-duration: 5s # Cualquier respuesta que tarde mas de 2s se considera fallo
gateway:
  retry:
    attempts: 3